### ISSUE TITLE
Blank characters appear when code is too long

### ISSUE THREAD

**Issue by EnzoTools** [EnlighterJS/Plugin.WordPress#111]
The EnlighterJS is a great plug-in
But I found some problems when I used it... 

When the code is too long it will appear blank
for example：
normal
![11](https://user-images.githubusercontent.com/17564454/44484280-f1a54e00-a67f-11e8-8ec1-670984b93929.png)

When the code is long or the screen is narrow(phone)
![22](https://user-images.githubusercontent.com/17564454/44484361-2ca78180-a680-11e8-8776-88ee3c17aab5.png)

look forward to your reply
thank you

**Comment by EnzoTools** [comment]
I can use my phone to check my blog
https://github.xin/37
https://github.xin/91

**Comment by AndiDittrich** [comment]
Hi @EnzoTools ,

the issue is caused by your themes css `text-align` setting:

```css
.text-justify-on .widget_ui_posts .text, .text-justify-on .widget_ui_textasb, .text-justify-on .relates li, .text-justify-on .article-content, .text-justify-on .widget_ui_comments ul li, .text-justify-on .excerpt .note, .text-justify-on .excerpt-minic .note {
text-align: justify;
}
```

you can fix this by explicit setting it to **left** for EnlighterJS:

```css
.EnlighterJS, .EnlighterJSWrapper {
text-align:left;
}
```

best regards, Andi
