### ISSUE TITLE
Bottom margin creates large gap

### ISSUE THREAD

**Issue by marcingminski** [EnlighterJS/Plugin.WordPress#118]
Hi, 

I noticed in some cases EnlighterJS creates a large gap between an object beneath:
![image](https://user-images.githubusercontent.com/8288333/45264016-142fb900-b42d-11e8-8f5b-dac1d51a78e9.png)

This looks to be caused by the 20px margin in:
```css
ol.EnlighterJS, ul.EnlighterJS {
    display: block;
    font-size: 10px;
    background-color: #f2f2f2;
    color: #939393;
    margin: 0 0 20px;
    padding: 0;
    text-indent: 0;
    list-style: none;
}
```
When I remove the 20px margin from the above and add it do the wrapper container it seems to work ok:
```css
.EnlighterJSWrapper {
    margin-bottom: 20px;
}
```
![image](https://user-images.githubusercontent.com/8288333/45264025-3c1f1c80-b42d-11e8-897b-289cdc2a2dd2.png)

I have not noticed any side effects but I am not a web developer though so not sure of the exact implication. 

You can see it here: https://sqlwatch.io/docs/installation/collation-conflict/

Great plugin btw!
Thanks
