### ISSUE TITLE
Twenty Twenty Theme: Not aligned with the rest of the text, suggested workaround doesn't work anymore

### ISSUE THREAD

**Issue by laurinneff** [EnlighterJS/Plugin.WordPress#309]
I know this was reported before, but I'm bringing this up again since the fix suggested [here](https://github.com/EnlighterJS/documentation/blob/master/wordpress/WPThemeCompatibility.md) doesn't work anymore after updating to v4.4.0. I needed to change it to this:
```css
.enlighter-default {
    margin: 0 auto 1.25em auto !important;
}
```
and then it works again
