### ISSUE TITLE
Crayon Syntax Highlighter parsing creates malformed whitespace

### ISSUE THREAD

**Issue by dmadison** [EnlighterJS/Plugin.WordPress#351]
Hi, I'm trying to switch a site from Crayon Syntax Highlighter to Enlighter and I'm running into an issue where text following a code block is not enclosed within paragraph tags and spurious breaks are introduced.

#### Steps to reproduce:
1. Install WordPress (latest, 5.9.3)
2. Install Classic Editor plugin (latest, 1.6.2) and activate
3. Install Enlighter (latest, 4.5.0) and activate
4. In Enlighter options, enable compatibility mode and Crayon compatibility
5. Create a new post using the classic editor with the following content:
      ```html
    <h2>Hello World</h2>
    Let's try an example:
    <pre class="lang:cpp decode:true">#include &lt;iostream&gt;
    
    int main() {
        std::cout &lt;&lt; "Hello World!";
        return 0;
    }
    </pre>
    The example above prints "Hello World".
    ```
6. Publish the post and look at the result.

#### Expected Output:
```html
<p>Let’s try an example:</p>
<div class="enlighter-default"></div> <!--abridged--> 
<p>The example above prints “Hello World”.</p>
```

#### Actual Output:
```html
<p>Let’s try an example:
  <br>
</p>
<div class="enlighter-default"></div> <!--abridged--> 
<br>
The example above prints “Hello World”.
<p></p>
```

<details>
<summary>Full Output</summary>

```html
<p>Let’s try an example:<br></p>
<div class="enlighter-default enlighter-v-standard enlighter-t-enlighter enlighter-hover enlighter-linenumbers ">
  <div class="enlighter-toolbar-top enlighter-toolbar">
    <div class="enlighter-btn enlighter-btn-raw" title="Plain text"></div>
    <div class="enlighter-btn enlighter-btn-copy" title="Copy to clipboard"></div>
    <div class="enlighter-btn enlighter-btn-window" title="Open code in new window"></div>
    <div class="enlighter-btn enlighter-btn-website" title="EnlighterJS 3 Syntax Highlighter"></div>
  </div>
  <div class="enlighter" style="">
    <div class="">
      <div><span class="enlighter-k4">#include &lt;iostream&gt;</span><span class="enlighter-text"></span></div>
    </div>
    <div class="">
      <div><span class="enlighter-text"></span></div>
    </div>
    <div class="">
      <div><span class="enlighter-text"></span><span class="enlighter-k5">int</span><span class="enlighter-text"> </span><span class="enlighter-m0">main</span><span class="enlighter-g1">()</span><span class="enlighter-text"> </span><span class="enlighter-g1">{</span><span class="enlighter-text"></span></div>
    </div>
    <div class="">
      <div><span class="enlighter-text">  std::cout </span><span class="enlighter-g1">&lt;&lt;</span><span class="enlighter-text"> </span><span class="enlighter-s0">"Hello World!"</span><span class="enlighter-text">;</span></div>
    </div>
    <div class="">
      <div><span class="enlighter-text">  </span><span class="enlighter-k0">return</span><span class="enlighter-text"> 0;</span></div>
    </div>
    <div class="">
      <div><span class="enlighter-text"></span><span class="enlighter-g1">}</span></div>
    </div>
  </div>
  <div class="enlighter-raw">#include &lt;iostream&gt;
    int main() {
    std::cout &lt;&lt; "Hello World!";
    return 0;
    }
  </div>
  <div class="enlighter-toolbar-bottom enlighter-toolbar"></div>
</div>
<pre class="EnlighterJSRAW enlighter-origin" data-enlighter-language="cpp" data-enlighter-title="">#include &lt;iostream&gt;

int main() {
  std::cout &lt;&lt; "Hello World!";
  return 0;
}
</pre>
<br>
The example above prints “Hello World”.
<p></p>
```
</details>

On my own website's theme this creates terrible whitespace problems. On the default Twenty-Twenty Two theme this pushes the next line outside the width of the post text:

![enlighter-demo](https://user-images.githubusercontent.com/24282108/168793515-ecd9404c-23c0-4a5e-b4e2-1ae5a8c1e811.png)

---

This only appears to be a problem with legacy posts using the classic editor. The same content using the block editor is parsed fine and matches the expected output above.

<details>
<summary>Block editor post source</summary>

```html
<!-- wp:heading -->
<h2>Hello World</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Let's try an example:</p>
<!-- /wp:paragraph -->

<!-- wp:preformatted -->
<pre class="lang:cpp decode:true">#include &lt;iostream&gt;

int main() {
    std::cout &lt;&lt; "Hello World!";
    return 0;
}
</pre>
<!-- /wp:preformatted -->

<!-- wp:paragraph -->
<p>The example above prints "Hello World".</p>
<!-- /wp:paragraph -->
```
</details>

**Comment by AndiDittrich** [comment]
Hi @dmadison 

i'm unable to reproduce your issue:

-------

## Editor

![image](https://user-images.githubusercontent.com/1474107/168895300-49346aee-73c8-4d90-9120-47bf6321dd7a.png)

--------

## Result

![image](https://user-images.githubusercontent.com/1474107/168895358-ee97e995-a062-4abe-a5bb-c887ef8fece0.png)

------

## Page source

![image](https://user-images.githubusercontent.com/1474107/168895639-3ee4b131-5952-48af-bd4f-ede1ba8d0ae0.png)

**Comment by dmadison** [comment]
How strange. I've tested with two installs (the existing site and the minimally reproducible example) and both have the same issue.

Your entry content looks slimmer than my full output. Could this be caused by a configuration difference?

Here is the MRE `docker-compose` file in case it's helpful:

<details>
<summary>docker-compose.yml</summary>

```yml
services:
  wordpress:
    image: wordpress:5.9.3-apache
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - type: bind
        source: ./site
        target: /var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/mysql

volumes:
  wordpress:
  db:
```
</details>
