### ISSUE TITLE
Guide to change the font size for inline code

### ISSUE THREAD

**Issue by westerdaled** [EnlighterJS/Plugin.WordPress#377]
I want to increase the font size to the value shown in image highlight from the default `1em`.  However, I don't seem to acheive this when setting similar values in the Enlighter customizer base theme settings. Is there another setting I should adjust ?

![image](https://github.com/EnlighterJS/Plugin.WordPress/assets/937208/56872c9a-dbe1-4ca0-952d-7aa4e4f2518c)

**Comment by AndiDittrich** [comment]
to change the font-sizes of different views independently you've to match the views:

```css
.enlighter-v-standard .enlighter span{
  font-size: 1.1rem;
}

.enlighter-v-inline .enlighter span{
  font-size: 1.3rem;
}
```
