### ISSUE TITLE
How to escape Enlighter from custom CSS?

### ISSUE THREAD

**Issue by parthi2929** [EnlighterJS/Plugin.WordPress#98]
Hi

I have restored to visual, and your plugin is working great. I wanted to apply some global font style in my pages but that was also affecting enlighter. Can you please suggest, how could I avoid your specific part alone?

```css
ol:not(#EnlighterJS) li, p, table
{
	font-family: 'Arial';
	color:#303030;
	font-size:15px;
	line-height:22.5px;
	font-weight:400;
}
```

With above code, even when I try to exclude EnlighterJS, the code appears to get influenced (for eg, gets Arial font instead of its own default).
